# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5cd57c9e80f5ad98c8ea122568c708f5513c17f1f30a9fde021be9a5af9c178e20781cac571a77424ab36cb9fbb469f56108e55de4731605eccf43f6977c9ab

test:
  secret_key_base: 6fbca9254a0c8b46b5f645ac72ce983f45eb2561e828934bbe88acff35b80fb34a9e7bed30c4d8e4dd9588aa5f42ea207c30f75f3118ab21578fdd03d4005343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
